### PR TITLE
Akash branch

### PR DESCRIPTION
**Pull request by Akashkharita**
Adding the pytorch version

### CODE REVIEW

**Review by zepam — DISMISSED** [review]
pytorch code conversion review

**Comment by zepam** [comment]
@Akashkharita could you pull the original file (ClusTremor.ipynb) out of the commit?

We can leave the original file untouched and review the changes on the updated file ClusTremor_Pytorch.ipynb.

**Comment by Akashkharita** [comment]
Got it! Restored the original file to previous version.

**Review by zepam — APPROVED** [review]
pytorch update for review

**Pull request merged**
